rule win_ransomexx_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2021-10-07"
        version = "1"
        description = "Detects win.ransomexx."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.ransomexx"
        malpedia_rule_date = "20211007"
        malpedia_hash = "e5b790e0f888f252d49063a1251ca60ec2832535"
        malpedia_version = "20211008"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 56 8d85a4f9ffff 7809 8bf7 e8???????? eb05 e8???????? }
            // n = 7, score = 100
            //   56                   | push                esi
            //   8d85a4f9ffff         | lea                 eax, dword ptr [ebp - 0x65c]
            //   7809                 | js                  0xb
            //   8bf7                 | mov                 esi, edi
            //   e8????????           |                     
            //   eb05                 | jmp                 7
            //   e8????????           |                     

        $sequence_1 = { 8d430f 8d4900 fe00 7508 48 8d1407 85d2 }
            // n = 7, score = 100
            //   8d430f               | lea                 eax, dword ptr [ebx + 0xf]
            //   8d4900               | lea                 ecx, dword ptr [ecx]
            //   fe00                 | inc                 byte ptr [eax]
            //   7508                 | jne                 0xa
            //   48                   | dec                 eax
            //   8d1407               | lea                 edx, dword ptr [edi + eax]
            //   85d2                 | test                edx, edx

        $sequence_2 = { 8bcc 33c0 3bc8 0f84eb000000 8bd1 81ea???????? 42 }
            // n = 7, score = 100
            //   8bcc                 | mov                 ecx, esp
            //   33c0                 | xor                 eax, eax
            //   3bc8                 | cmp                 ecx, eax
            //   0f84eb000000         | je                  0xf1
            //   8bd1                 | mov                 edx, ecx
            //   81ea????????         |                     
            //   42                   | inc                 edx

        $sequence_3 = { 8bff 8b30 8d55fc 52 6a00 56 }
            // n = 6, score = 100
            //   8bff                 | mov                 edi, edi
            //   8b30                 | mov                 esi, dword ptr [eax]
            //   8d55fc               | lea                 edx, dword ptr [ebp - 4]
            //   52                   | push                edx
            //   6a00                 | push                0
            //   56                   | push                esi

        $sequence_4 = { 83c404 85f6 0f85f6010000 8b4df0 8d45d0 50 8b45f4 }
            // n = 7, score = 100
            //   83c404               | add                 esp, 4
            //   85f6                 | test                esi, esi
            //   0f85f6010000         | jne                 0x1fc
            //   8b4df0               | mov                 ecx, dword ptr [ebp - 0x10]
            //   8d45d0               | lea                 eax, dword ptr [ebp - 0x30]
            //   50                   | push                eax
            //   8b45f4               | mov                 eax, dword ptr [ebp - 0xc]

        $sequence_5 = { 41 4e 75f7 8b5df4 83c728 85d2 }
            // n = 6, score = 100
            //   41                   | inc                 ecx
            //   4e                   | dec                 esi
            //   75f7                 | jne                 0xfffffff9
            //   8b5df4               | mov                 ebx, dword ptr [ebp - 0xc]
            //   83c728               | add                 edi, 0x28
            //   85d2                 | test                edx, edx

        $sequence_6 = { b9???????? 8d85e4feffff 8d4900 8a10 3a11 751a 84d2 }
            // n = 7, score = 100
            //   b9????????           |                     
            //   8d85e4feffff         | lea                 eax, dword ptr [ebp - 0x11c]
            //   8d4900               | lea                 ecx, dword ptr [ecx]
            //   8a10                 | mov                 dl, byte ptr [eax]
            //   3a11                 | cmp                 dl, byte ptr [ecx]
            //   751a                 | jne                 0x1c
            //   84d2                 | test                dl, dl

        $sequence_7 = { 8bec 83ec0c 53 56 c745fc00000000 85ff 0f84c1000000 }
            // n = 7, score = 100
            //   8bec                 | mov                 ebp, esp
            //   83ec0c               | sub                 esp, 0xc
            //   53                   | push                ebx
            //   56                   | push                esi
            //   c745fc00000000       | mov                 dword ptr [ebp - 4], 0
            //   85ff                 | test                edi, edi
            //   0f84c1000000         | je                  0xc7

        $sequence_8 = { 6a00 6880000008 6a03 6a00 6a00 68000000c0 57 }
            // n = 7, score = 100
            //   6a00                 | push                0
            //   6880000008           | push                0x8000080
            //   6a03                 | push                3
            //   6a00                 | push                0
            //   6a00                 | push                0
            //   68000000c0           | push                0xc0000000
            //   57                   | push                edi

        $sequence_9 = { 0fb6530c 885704 0fb6430d 884705 0fb64b0e }
            // n = 5, score = 100
            //   0fb6530c             | movzx               edx, byte ptr [ebx + 0xc]
            //   885704               | mov                 byte ptr [edi + 4], dl
            //   0fb6430d             | movzx               eax, byte ptr [ebx + 0xd]
            //   884705               | mov                 byte ptr [edi + 5], al
            //   0fb64b0e             | movzx               ecx, byte ptr [ebx + 0xe]

    condition:
        7 of them and filesize < 372736
}