rule win_btcware_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2021-10-07"
        version = "1"
        description = "Detects win.btcware."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.btcware"
        malpedia_rule_date = "20211007"
        malpedia_hash = "e5b790e0f888f252d49063a1251ca60ec2832535"
        malpedia_version = "20211008"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 83f904 0f82206effff 83f923 0f87176effff }
            // n = 4, score = 100
            //   83f904               | cmp                 ecx, 4
            //   0f82206effff         | jb                  0xffff6e26
            //   83f923               | cmp                 ecx, 0x23
            //   0f87176effff         | ja                  0xffff6e1d

        $sequence_1 = { 3bc8 730b 50 8bce e8???????? 8a55f3 837e1410 }
            // n = 7, score = 100
            //   3bc8                 | cmp                 ecx, eax
            //   730b                 | jae                 0xd
            //   50                   | push                eax
            //   8bce                 | mov                 ecx, esi
            //   e8????????           |                     
            //   8a55f3               | mov                 dl, byte ptr [ebp - 0xd]
            //   837e1410             | cmp                 dword ptr [esi + 0x14], 0x10

        $sequence_2 = { 02d1 8ac4 8855ec 8a55f2 8aca c0e004 c0e902 }
            // n = 7, score = 100
            //   02d1                 | add                 dl, cl
            //   8ac4                 | mov                 al, ah
            //   8855ec               | mov                 byte ptr [ebp - 0x14], dl
            //   8a55f2               | mov                 dl, byte ptr [ebp - 0xe]
            //   8aca                 | mov                 cl, dl
            //   c0e004               | shl                 al, 4
            //   c0e902               | shr                 cl, 2

        $sequence_3 = { 8bd6 8b4610 47 881c02 ff4610 8b4e10 }
            // n = 6, score = 100
            //   8bd6                 | mov                 edx, esi
            //   8b4610               | mov                 eax, dword ptr [esi + 0x10]
            //   47                   | inc                 edi
            //   881c02               | mov                 byte ptr [edx + eax], bl
            //   ff4610               | inc                 dword ptr [esi + 0x10]
            //   8b4e10               | mov                 ecx, dword ptr [esi + 0x10]

        $sequence_4 = { 0f82dc000000 8b7d10 2bc8 3bcf }
            // n = 4, score = 100
            //   0f82dc000000         | jb                  0xe2
            //   8b7d10               | mov                 edi, dword ptr [ebp + 0x10]
            //   2bc8                 | sub                 ecx, eax
            //   3bcf                 | cmp                 ecx, edi

        $sequence_5 = { 0f82a070ffff 83f923 0f879770ffff 8bc8 51 }
            // n = 5, score = 100
            //   0f82a070ffff         | jb                  0xffff70a6
            //   83f923               | cmp                 ecx, 0x23
            //   0f879770ffff         | ja                  0xffff709d
            //   8bc8                 | mov                 ecx, eax
            //   51                   | push                ecx

        $sequence_6 = { 6bc830 8b049540d04100 f644082801 7422 8d4508 }
            // n = 5, score = 100
            //   6bc830               | imul                ecx, eax, 0x30
            //   8b049540d04100       | mov                 eax, dword ptr [edx*4 + 0x41d040]
            //   f644082801           | test                byte ptr [eax + ecx + 0x28], 1
            //   7422                 | je                  0x24
            //   8d4508               | lea                 eax, dword ptr [ebp + 8]

        $sequence_7 = { 03c3 51 50 e8???????? 8b45fc }
            // n = 5, score = 100
            //   03c3                 | add                 eax, ebx
            //   51                   | push                ecx
            //   50                   | push                eax
            //   e8????????           |                     
            //   8b45fc               | mov                 eax, dword ptr [ebp - 4]

        $sequence_8 = { 8d84248c000000 68???????? 50 ff15???????? 83c40c 8d842488000000 68???????? }
            // n = 7, score = 100
            //   8d84248c000000       | lea                 eax, dword ptr [esp + 0x8c]
            //   68????????           |                     
            //   50                   | push                eax
            //   ff15????????         |                     
            //   83c40c               | add                 esp, 0xc
            //   8d842488000000       | lea                 eax, dword ptr [esp + 0x88]
            //   68????????           |                     

        $sequence_9 = { 83f810 7245 8b8df0feffff 40 }
            // n = 4, score = 100
            //   83f810               | cmp                 eax, 0x10
            //   7245                 | jb                  0x47
            //   8b8df0feffff         | mov                 ecx, dword ptr [ebp - 0x110]
            //   40                   | inc                 eax

    condition:
        7 of them and filesize < 458752
}