rule win_outlook_backdoor_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2021-10-07"
        version = "1"
        description = "Detects win.outlook_backdoor."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.outlook_backdoor"
        malpedia_rule_date = "20211007"
        malpedia_hash = "e5b790e0f888f252d49063a1251ca60ec2832535"
        malpedia_version = "20211008"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 8d7db0 e8???????? eb21 2b5d14 ff751c 8d7b01 8d75b0 }
            // n = 7, score = 500
            //   8d7db0               | lea                 edi, dword ptr [ebp - 0x50]
            //   e8????????           |                     
            //   eb21                 | jmp                 0x23
            //   2b5d14               | sub                 ebx, dword ptr [ebp + 0x14]
            //   ff751c               | push                dword ptr [ebp + 0x1c]
            //   8d7b01               | lea                 edi, dword ptr [ebx + 1]
            //   8d75b0               | lea                 esi, dword ptr [ebp - 0x50]

        $sequence_1 = { 034608 83781810 7205 8b4004 eb03 83c004 50 }
            // n = 7, score = 500
            //   034608               | add                 eax, dword ptr [esi + 8]
            //   83781810             | cmp                 dword ptr [eax + 0x18], 0x10
            //   7205                 | jb                  7
            //   8b4004               | mov                 eax, dword ptr [eax + 4]
            //   eb03                 | jmp                 5
            //   83c004               | add                 eax, 4
            //   50                   | push                eax

        $sequence_2 = { 8bce e8???????? 8bd8 8d442420 8bce }
            // n = 5, score = 500
            //   8bce                 | mov                 ecx, esi
            //   e8????????           |                     
            //   8bd8                 | mov                 ebx, eax
            //   8d442420             | lea                 eax, dword ptr [esp + 0x20]
            //   8bce                 | mov                 ecx, esi

        $sequence_3 = { 25c0010000 83f840 7425 ff7514 8d75e8 ff7518 ff7510 }
            // n = 7, score = 500
            //   25c0010000           | and                 eax, 0x1c0
            //   83f840               | cmp                 eax, 0x40
            //   7425                 | je                  0x27
            //   ff7514               | push                dword ptr [ebp + 0x14]
            //   8d75e8               | lea                 esi, dword ptr [ebp - 0x18]
            //   ff7518               | push                dword ptr [ebp + 0x18]
            //   ff7510               | push                dword ptr [ebp + 0x10]

        $sequence_4 = { 51 034510 8bcf 50 8945fc e8???????? 84c0 }
            // n = 7, score = 500
            //   51                   | push                ecx
            //   034510               | add                 eax, dword ptr [ebp + 0x10]
            //   8bcf                 | mov                 ecx, edi
            //   50                   | push                eax
            //   8945fc               | mov                 dword ptr [ebp - 4], eax
            //   e8????????           |                     
            //   84c0                 | test                al, al

        $sequence_5 = { 8365fc00 8d4608 e8???????? 5e 85c0 7409 8d4dd4 }
            // n = 7, score = 500
            //   8365fc00             | and                 dword ptr [ebp - 4], 0
            //   8d4608               | lea                 eax, dword ptr [esi + 8]
            //   e8????????           |                     
            //   5e                   | pop                 esi
            //   85c0                 | test                eax, eax
            //   7409                 | je                  0xb
            //   8d4dd4               | lea                 ecx, dword ptr [ebp - 0x2c]

        $sequence_6 = { c3 57 6a2c e8???????? 8bf8 59 85ff }
            // n = 7, score = 500
            //   c3                   | ret                 
            //   57                   | push                edi
            //   6a2c                 | push                0x2c
            //   e8????????           |                     
            //   8bf8                 | mov                 edi, eax
            //   59                   | pop                 ecx
            //   85ff                 | test                edi, edi

        $sequence_7 = { 895c2410 8d442410 50 53 6802100100 c684249800000001 ff742420 }
            // n = 7, score = 500
            //   895c2410             | mov                 dword ptr [esp + 0x10], ebx
            //   8d442410             | lea                 eax, dword ptr [esp + 0x10]
            //   50                   | push                eax
            //   53                   | push                ebx
            //   6802100100           | push                0x11002
            //   c684249800000001     | mov                 byte ptr [esp + 0x98], 1
            //   ff742420             | push                dword ptr [esp + 0x20]

        $sequence_8 = { eb02 33c0 8bf0 ff75f0 ff15???????? 5f 8bc6 }
            // n = 7, score = 500
            //   eb02                 | jmp                 4
            //   33c0                 | xor                 eax, eax
            //   8bf0                 | mov                 esi, eax
            //   ff75f0               | push                dword ptr [ebp - 0x10]
            //   ff15????????         |                     
            //   5f                   | pop                 edi
            //   8bc6                 | mov                 eax, esi

        $sequence_9 = { e8???????? 83ec38 56 57 8bf1 8b4604 33ff }
            // n = 7, score = 500
            //   e8????????           |                     
            //   83ec38               | sub                 esp, 0x38
            //   56                   | push                esi
            //   57                   | push                edi
            //   8bf1                 | mov                 esi, ecx
            //   8b4604               | mov                 eax, dword ptr [esi + 4]
            //   33ff                 | xor                 edi, edi

    condition:
        7 of them and filesize < 2912256
}