rule win_hookinjex_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2021-10-07"
        version = "1"
        description = "Detects win.hookinjex."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.hookinjex"
        malpedia_rule_date = "20211007"
        malpedia_hash = "e5b790e0f888f252d49063a1251ca60ec2832535"
        malpedia_version = "20211008"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 833d????????00 7411 b906000000 e8???????? 488905???????? }
            // n = 5, score = 300
            //   833d????????00       |                     
            //   7411                 | inc                 ebp
            //   b906000000           | xor                 ecx, ecx
            //   e8????????           |                     
            //   488905????????       |                     

        $sequence_1 = { 833d????????00 7411 b903000000 e8???????? }
            // n = 4, score = 300
            //   833d????????00       |                     
            //   7411                 | mov                 ecx, 6
            //   b903000000           | je                  0x13
            //   e8????????           |                     

        $sequence_2 = { e8???????? e8???????? b801000000 e9???????? 4533c9 }
            // n = 5, score = 300
            //   e8????????           |                     
            //   e8????????           |                     
            //   b801000000           | dec                 eax
            //   e9????????           |                     
            //   4533c9               | mov                 ecx, dword ptr [esp + 0x58]

        $sequence_3 = { e8???????? 488b4c2458 e8???????? 488b4c2458 e8???????? 33c0 }
            // n = 6, score = 300
            //   e8????????           |                     
            //   488b4c2458           | cmp                 eax, 5
            //   e8????????           |                     
            //   488b4c2458           | dec                 eax
            //   e8????????           |                     
            //   33c0                 | mov                 ecx, dword ptr [esp + 0x58]

        $sequence_4 = { e8???????? 488bc8 e8???????? 83f805 }
            // n = 4, score = 300
            //   e8????????           |                     
            //   488bc8               | dec                 eax
            //   e8????????           |                     
            //   83f805               | mov                 ecx, eax

        $sequence_5 = { e8???????? 488905???????? c705????????01000000 33c0 }
            // n = 4, score = 300
            //   e8????????           |                     
            //   488905????????       |                     
            //   c705????????01000000     |     
            //   33c0                 | xor                 eax, eax

        $sequence_6 = { e9???????? 488b4c2458 e8???????? 488b4c2450 }
            // n = 4, score = 300
            //   e9????????           |                     
            //   488b4c2458           | xor                 eax, eax
            //   e8????????           |                     
            //   488b4c2450           | mov                 eax, 1

        $sequence_7 = { e8???????? 33c9 e8???????? 488905???????? }
            // n = 4, score = 300
            //   e8????????           |                     
            //   33c9                 | xor                 ecx, ecx
            //   e8????????           |                     
            //   488905????????       |                     

        $sequence_8 = { 2500100000 89842450010000 83bc245001000000 746d }
            // n = 4, score = 200
            //   2500100000           | je                  0x81
            //   89842450010000       | mov                 eax, dword ptr [esp + 0x20]
            //   83bc245001000000     | and                 eax, 0x8000
            //   746d                 | and                 eax, 0x1000

        $sequence_9 = { 2500180000 3d00080000 750a c744246c01000000 }
            // n = 4, score = 200
            //   2500180000           | je                  0x250
            //   3d00080000           | mov                 eax, dword ptr [esp + 0x20]
            //   750a                 | and                 eax, 0x8000
            //   c744246c01000000     | and                 eax, 0x1000

        $sequence_10 = { 2500100000 898424a8010000 83bc24a801000000 0f84e4010000 }
            // n = 4, score = 200
            //   2500100000           | je                  0x1cf
            //   898424a8010000       | mov                 eax, dword ptr [esp + 0x20]
            //   83bc24a801000000     | and                 eax, 0x8000
            //   0f84e4010000         | and                 eax, 0x1000

        $sequence_11 = { 2500100000 898424d8000000 83bc24d800000000 0f843b020000 }
            // n = 4, score = 200
            //   2500100000           | je                  0x1f9
            //   898424d8000000       | mov                 eax, dword ptr [esp + 0x20]
            //   83bc24d800000000     | and                 eax, 0x8000
            //   0f843b020000         | and                 eax, 0x1000

        $sequence_12 = { 2500100000 89842438010000 83bc243801000000 7470 }
            // n = 4, score = 200
            //   2500100000           | je                  0x7a
            //   89842438010000       | mov                 eax, dword ptr [esp + 0x20]
            //   83bc243801000000     | and                 eax, 0x8000
            //   7470                 | and                 eax, 0x1000

        $sequence_13 = { 2500100000 89842420010000 83bc242001000000 7470 }
            // n = 4, score = 200
            //   2500100000           | je                  0x13
            //   89842420010000       | mov                 ecx, 3
            //   83bc242001000000     | je                  0x13
            //   7470                 | mov                 ecx, 3

        $sequence_14 = { 2500100000 89842468010000 83bc246801000000 0f84dc000000 }
            // n = 4, score = 200
            //   2500100000           | je                  0x7e
            //   89842468010000       | mov                 eax, dword ptr [esp + 0x20]
            //   83bc246801000000     | and                 eax, 0x8000
            //   0f84dc000000         | and                 eax, 0x1000

        $sequence_15 = { 2500100000 89842490000000 83bc249000000000 0f84ba010000 }
            // n = 4, score = 200
            //   2500100000           | je                  0xf1
            //   89842490000000       | mov                 eax, dword ptr [esp + 0x20]
            //   83bc249000000000     | and                 eax, 0x8000
            //   0f84ba010000         | and                 eax, 0x1000

    condition:
        7 of them and filesize < 6545408
}